import Foundation

struct ClockEntry: Identifiable, Codable, Hashable {
    let id: UUID
    var timeZoneIdentifier: String
    var cityLabel: String
    var airportCode: String
    var sortOrder: Int

    var timeZone: TimeZone {
        TimeZone(identifier: timeZoneIdentifier) ?? .current
    }

    init(id: UUID = UUID(), timeZoneIdentifier: String, cityLabel: String, airportCode: String? = nil, sortOrder: Int) {
        self.id = id
        self.timeZoneIdentifier = timeZoneIdentifier
        self.cityLabel = cityLabel
        self.airportCode = airportCode
            ?? Self.iataCode(for: timeZoneIdentifier)
            ?? String(cityLabel.prefix(3)).uppercased()
        self.sortOrder = sortOrder
    }

    // Backward-compatible decoder: airportCode may be missing in data stored before this field was added
    enum CodingKeys: String, CodingKey {
        case id, timeZoneIdentifier, cityLabel, airportCode, sortOrder
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(UUID.self, forKey: .id)
        timeZoneIdentifier = try c.decode(String.self, forKey: .timeZoneIdentifier)
        cityLabel = try c.decode(String.self, forKey: .cityLabel)
        sortOrder = try c.decode(Int.self, forKey: .sortOrder)
        let stored = try c.decodeIfPresent(String.self, forKey: .airportCode)
        airportCode = stored
            ?? Self.iataCode(for: timeZoneIdentifier)
            ?? String(cityLabel.prefix(3)).uppercased()
    }

    var utcOffsetString: String {
        let seconds = timeZone.secondsFromGMT(for: Date())
        let hours = seconds / 3600
        let minutes = abs(seconds % 3600) / 60
        if minutes == 0 {
            return hours >= 0 ? "UTC+\(hours)" : "UTC\(hours)"
        } else {
            return hours >= 0 ? "UTC+\(hours):\(String(format: "%02d", minutes))" : "UTC\(hours):\(String(format: "%02d", minutes))"
        }
    }

    static func iataCode(for tzIdentifier: String) -> String? {
        iataMap[tzIdentifier]
    }

    // swiftlint:disable:next large_tuple
    static let iataMap: [String: String] = [
        // North America
        "America/New_York": "NYC",
        "America/Chicago": "CHI",
        "America/Denver": "DEN",
        "America/Los_Angeles": "LAX",
        "America/Phoenix": "PHX",
        "America/Anchorage": "ANC",
        "America/Adak": "ADK",
        "America/Nome": "OME",
        "America/Sitka": "SIT",
        "America/Juneau": "JNU",
        "America/Yakutat": "YAK",
        "America/Toronto": "YTO",
        "America/Vancouver": "YVR",
        "America/Montreal": "YMQ",
        "America/Calgary": "YYC",
        "America/Edmonton": "YEG",
        "America/Winnipeg": "YWG",
        "America/Halifax": "YHZ",
        "America/St_Johns": "YYT",
        "America/Regina": "YQR",
        "America/Whitehorse": "YXY",
        "America/Yellowknife": "YZF",
        "America/Mexico_City": "MEX",
        "America/Cancun": "CUN",
        "America/Guadalajara": "GDL",
        "America/Monterrey": "MTY",
        "America/Tijuana": "TIJ",
        "America/Merida": "MID",
        "America/Hermosillo": "HMO",
        "America/Mazatlan": "MZT",
        "America/Bahia_Banderas": "PVR",
        "America/Chihuahua": "CUU",
        "America/Ciudad_Juarez": "CJS",
        "America/Ojinaga": "OJG",
        "America/Belize": "BZE",
        "America/Guatemala": "GUA",
        "America/El_Salvador": "SAL",
        "America/Tegucigalpa": "TGU",
        "America/Managua": "MGA",
        "America/Costa_Rica": "SJO",
        "America/Panama": "PTY",
        "America/Havana": "HAV",
        "America/Port-au-Prince": "PAP",
        "America/Santo_Domingo": "SDQ",
        "America/Puerto_Rico": "SJU",
        "America/Jamaica": "KIN",
        "America/Nassau": "NAS",
        "America/Barbados": "BGI",
        "America/Port_of_Spain": "POS",
        "America/Curacao": "CUR",
        "America/Aruba": "AUA",
        "America/Martinique": "FDF",
        "America/Guadeloupe": "PTP",
        "America/Bogota": "BOG",
        "America/Lima": "LIM",
        "America/Sao_Paulo": "GRU",
        "America/Manaus": "MAO",
        "America/Belem": "BEL",
        "America/Fortaleza": "FOR",
        "America/Recife": "REC",
        "America/Bahia": "SSA",
        "America/Cuiaba": "CGB",
        "America/Boa_Vista": "BVB",
        "America/Rio_Branco": "RBR",
        "America/Porto_Velho": "PVH",
        "America/Noronha": "FEN",
        "America/Argentina/Buenos_Aires": "EZE",
        "America/Argentina/Cordoba": "COR",
        "America/Argentina/Salta": "SLA",
        "America/Argentina/Mendoza": "MDZ",
        "America/Argentina/Tucuman": "TUC",
        "America/Argentina/Rosario": "ROS",
        "America/Argentina/San_Luis": "LUQ",
        "America/Argentina/San_Juan": "UAQ",
        "America/Argentina/Jujuy": "JUJ",
        "America/Argentina/Catamarca": "CTC",
        "America/Argentina/La_Rioja": "IRJ",
        "America/Argentina/Rio_Gallegos": "RGL",
        "America/Argentina/Ushuaia": "USH",
        "America/Santiago": "SCL",
        "America/Punta_Arenas": "PUQ",
        "America/Caracas": "CCS",
        "America/Guayaquil": "GYE",
        "America/Guyana": "GEO",
        "America/La_Paz": "LPB",
        "America/Asuncion": "ASU",
        "America/Montevideo": "MVD",
        "America/Cayenne": "CAY",
        "America/Paramaribo": "PBM",

        // Europe
        "Europe/London": "LON",
        "Europe/Paris": "PAR",
        "Europe/Berlin": "BER",
        "Europe/Madrid": "MAD",
        "Europe/Rome": "ROM",
        "Europe/Amsterdam": "AMS",
        "Europe/Brussels": "BRU",
        "Europe/Zurich": "ZRH",
        "Europe/Vienna": "VIE",
        "Europe/Stockholm": "STO",
        "Europe/Oslo": "OSL",
        "Europe/Copenhagen": "CPH",
        "Europe/Helsinki": "HEL",
        "Europe/Warsaw": "WAW",
        "Europe/Prague": "PRG",
        "Europe/Budapest": "BUD",
        "Europe/Athens": "ATH",
        "Europe/Istanbul": "IST",
        "Europe/Moscow": "MOW",
        "Europe/Lisbon": "LIS",
        "Europe/Dublin": "DUB",
        "Europe/Bucharest": "OTP",
        "Europe/Sofia": "SOF",
        "Europe/Zagreb": "ZAG",
        "Europe/Belgrade": "BEG",
        "Europe/Sarajevo": "SJJ",
        "Europe/Skopje": "SKP",
        "Europe/Tirane": "TIA",
        "Europe/Podgorica": "TGD",
        "Europe/Vilnius": "VNO",
        "Europe/Riga": "RIX",
        "Europe/Tallinn": "TLL",
        "Europe/Minsk": "MSQ",
        "Europe/Kyiv": "IEV",
        "Europe/Kiev": "IEV",
        "Europe/Chisinau": "KIV",
        "Europe/Luxembourg": "LUX",
        "Europe/Malta": "MLA",
        "Europe/Nicosia": "LCA",
        "Europe/Reykjavik": "KEF",
        "Atlantic/Reykjavik": "KEF",
        "Europe/Kaliningrad": "KGD",
        "Europe/Samara": "KUF",
        "Europe/Saratov": "GSV",
        "Europe/Ulyanovsk": "ULV",
        "Europe/Volgograd": "VOG",
        "Europe/Astrakhan": "ASF",
        "Europe/Simferopol": "SIP",
        "Europe/Uzhgorod": "UDJ",
        "Europe/Zaporozhye": "OZH",

        // Asia
        "Asia/Tokyo": "TYO",
        "Asia/Shanghai": "SHA",
        "Asia/Beijing": "BJS",
        "Asia/Hong_Kong": "HKG",
        "Asia/Seoul": "SEL",
        "Asia/Singapore": "SIN",
        "Asia/Taipei": "TPE",
        "Asia/Bangkok": "BKK",
        "Asia/Jakarta": "JKT",
        "Asia/Kuala_Lumpur": "KUL",
        "Asia/Manila": "MNL",
        "Asia/Mumbai": "BOM",
        "Asia/Kolkata": "CCU",
        "Asia/Delhi": "DEL",
        "Asia/Dubai": "DXB",
        "Asia/Riyadh": "RUH",
        "Asia/Karachi": "KHI",
        "Asia/Dhaka": "DAC",
        "Asia/Colombo": "CMB",
        "Asia/Kathmandu": "KTM",
        "Asia/Yangon": "RGN",
        "Asia/Ho_Chi_Minh": "SGN",
        "Asia/Phnom_Penh": "PNH",
        "Asia/Vientiane": "VTE",
        "Asia/Ulaanbaatar": "ULN",
        "Asia/Tashkent": "TAS",
        "Asia/Almaty": "ALA",
        "Asia/Bishkek": "FRU",
        "Asia/Tbilisi": "TBS",
        "Asia/Baku": "GYD",
        "Asia/Yerevan": "EVN",
        "Asia/Tehran": "IKA",
        "Asia/Baghdad": "BGW",
        "Asia/Amman": "AMM",
        "Asia/Beirut": "BEY",
        "Asia/Jerusalem": "TLV",
        "Asia/Tel_Aviv": "TLV",
        "Asia/Kuwait": "KWI",
        "Asia/Muscat": "MCT",
        "Asia/Bahrain": "BAH",
        "Asia/Qatar": "DOH",
        "Asia/Kabul": "KBL",
        "Asia/Aden": "ADE",
        "Asia/Sanaa": "SAH",
        "Asia/Macau": "MFM",
        "Asia/Pyongyang": "FNJ",
        "Asia/Chongqing": "CKG",
        "Asia/Urumqi": "URC",
        "Asia/Harbin": "HRB",
        "Asia/Brunei": "BWN",
        "Asia/Dili": "DIL",
        "Asia/Makassar": "UPG",
        "Asia/Jayapura": "DJJ",
        "Asia/Pontianak": "PNK",
        "Asia/Kuching": "KCH",
        "Asia/Kota_Kinabalu": "BKI",
        "Asia/Rangoon": "RGN",
        "Asia/Vladivostok": "VVO",
        "Asia/Magadan": "GDX",
        "Asia/Kamchatka": "PKC",
        "Asia/Sakhalin": "UUS",
        "Asia/Novosibirsk": "OVB",
        "Asia/Yekaterinburg": "SVX",
        "Asia/Omsk": "OMS",
        "Asia/Krasnoyarsk": "KJA",
        "Asia/Irkutsk": "IKT",
        "Asia/Yakutsk": "YKS",
        "Asia/Choibalsan": "COQ",
        "Asia/Hovd": "HVD",
        "Asia/Ashgabat": "ASB",
        "Asia/Samarkand": "SKD",
        "Asia/Dushanbe": "DYU",
        "Asia/Thimphu": "PBH",
        "Asia/Calcutta": "CCU",
        "Asia/Dacca": "DAC",
        "Asia/Anadyr": "DYR",
        "Asia/Srednekolymsk": "SEK",
        "Asia/Ust-Nera": "USR",
        "Asia/Chita": "HTA",
        "Asia/Khandyga": "KDY",

        // Australia & Pacific
        "Australia/Sydney": "SYD",
        "Australia/Melbourne": "MEL",
        "Australia/Brisbane": "BNE",
        "Australia/Perth": "PER",
        "Australia/Adelaide": "ADL",
        "Australia/Darwin": "DRW",
        "Australia/Hobart": "HBA",
        "Australia/Lord_Howe": "LDH",
        "Australia/Broken_Hill": "BHQ",
        "Australia/Lindeman": "LDC",
        "Australia/Currie": "CUF",
        "Pacific/Auckland": "AKL",
        "Pacific/Fiji": "NAN",
        "Pacific/Honolulu": "HNL",
        "Pacific/Guam": "GUM",
        "Pacific/Port_Moresby": "POM",
        "Pacific/Noumea": "NOU",
        "Pacific/Tahiti": "PPT",
        "Pacific/Pago_Pago": "PPG",
        "Pacific/Apia": "APW",
        "Pacific/Tongatapu": "TBU",
        "Pacific/Chatham": "CHT",
        "Pacific/Palau": "ROR",
        "Pacific/Chuuk": "TKK",
        "Pacific/Pohnpei": "PNI",
        "Pacific/Kosrae": "KSA",
        "Pacific/Majuro": "MAJ",
        "Pacific/Kwajalein": "KWA",
        "Pacific/Tarawa": "TRW",
        "Pacific/Nauru": "INU",
        "Pacific/Funafuti": "FUN",
        "Pacific/Fakaofo": "FKO",
        "Pacific/Rarotonga": "RAR",
        "Pacific/Marquesas": "NHV",
        "Pacific/Gambier": "GMR",
        "Pacific/Pitcairn": "PNL",
        "Pacific/Easter": "IPC",
        "Pacific/Galapagos": "GPS",
        "Pacific/Kiritimati": "CXI",

        // Africa
        "Africa/Cairo": "CAI",
        "Africa/Lagos": "LOS",
        "Africa/Nairobi": "NBO",
        "Africa/Johannesburg": "JNB",
        "Africa/Casablanca": "CMN",
        "Africa/Tunis": "TUN",
        "Africa/Algiers": "ALG",
        "Africa/Addis_Ababa": "ADD",
        "Africa/Accra": "ACC",
        "Africa/Khartoum": "KRT",
        "Africa/Dar_es_Salaam": "DAR",
        "Africa/Kampala": "EBB",
        "Africa/Kinshasa": "FIH",
        "Africa/Luanda": "LAD",
        "Africa/Lusaka": "LUN",
        "Africa/Harare": "HRE",
        "Africa/Maputo": "MPM",
        "Africa/Antananarivo": "TNR",
        "Africa/Tripoli": "TIP",
        "Africa/Bamako": "BKO",
        "Africa/Dakar": "DSS",
        "Africa/Abidjan": "ABJ",
        "Africa/Ouagadougou": "OUA",
        "Africa/Niamey": "NIM",
        "Africa/Ndjamena": "NDJ",
        "Africa/Douala": "DLA",
        "Africa/Libreville": "LBV",
        "Africa/Malabo": "SSG",
        "Africa/Brazzaville": "BZV",
        "Africa/Bangui": "BGF",
        "Africa/Bujumbura": "BJM",
        "Africa/Kigali": "KGL",
        "Africa/Mogadishu": "MGQ",
        "Africa/Djibouti": "JIB",
        "Africa/Asmara": "ASM",
        "Africa/Juba": "JUB",
        "Africa/Blantyre": "BLZ",
        "Africa/Mbabane": "MTS",
        "Africa/Maseru": "MSU",
        "Africa/Gaborone": "GBE",
        "Africa/Windhoek": "WDH",
        "Africa/Monrovia": "ROB",
        "Africa/Freetown": "FNA",
        "Africa/Conakry": "CKY",
        "Africa/Bissau": "OXB",
        "Africa/Banjul": "BJL",
        "Africa/Nouakchott": "NKC",
        "Africa/Timbuktu": "TOM",
        "Africa/Lome": "LFW",
        "Africa/Porto-Novo": "COO",
        "Africa/Sao_Tome": "TMS",
        "Africa/El_Aaiun": "EUN",
        "Africa/Ceuta": "JCU",

        // Atlantic & Indian Ocean
        "Atlantic/Azores": "TER",
        "Atlantic/Cape_Verde": "SID",
        "Atlantic/Canary": "TFN",
        "Atlantic/Madeira": "FNC",
        "Atlantic/Bermuda": "BDA",
        "Atlantic/Stanley": "PSY",
        "Atlantic/South_Georgia": "SGK",
        "Indian/Maldives": "MLE",
        "Indian/Mauritius": "MRU",
        "Indian/Reunion": "RUN",
        "Indian/Mayotte": "DZA",
        "Indian/Comoro": "HAH",
        "Indian/Christmas": "XCH",
        "Indian/Cocos": "CCK",
        "Indian/Mahe": "SEZ",
        "Indian/Antananarivo": "TNR",
    ]
}
